DROP TABLE IF EXISTS BROKERS;
--DROP TABLE IF EXISTS BROKERS_CONFIG;
DROP TABLE IF EXISTS SMS_REQUESTS;

/*
CREATE TABLE BROKERS_CONFIG (
	CFG_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CFG_TOKEN VARCHAR(100) NOT NULL,
	CFG_REQUEST_ENDPOINT VARCHAR(200) NOT NULL,
	CFG_NOTIFICATION_ENDPOINT VARCHAR(200) NULL
--	CONSTRAINT BROKERS_CONFIG_PK PRIMARY KEY (CFG_ID)
);
*/
CREATE TABLE BROKERS (
	BRK_CODE CHAR(3) NOT NULL PRIMARY KEY,
	BRK_NAME VARCHAR(50) NOT NULL,
	BRK_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
	BRK_WEIGHT TINYINT NOT NULL,
	BRK_TOKEN VARCHAR(100) NULL,
	BRK_REQUEST_ENDPOINT VARCHAR(200) NULL,
	CCC_NOTIFICATION_ENDPOINT VARCHAR(200) NULL,
	BRK_CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0) NOT NULL
--	BRK_CREATE_DATE BIGINT DEFAULT (EXTRACT(EPOCH from CURRENT_TIMESTAMP(0))) NOT NULL,
--	CFG_ID INTEGER NOT NULL
--	CONSTRAINT BROKERS_PK PRIMARY KEY (BRK_CODE)
);

CREATE TABLE ENTITIES (
	ENT_CODE CHAR(3) NOT NULL PRIMARY KEY,
	ENT_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE APPLICATIONS (
	APP_CODE CHAR(3) NOT NULL PRIMARY KEY,
	APP_NAME VARCHAR(50) NOT NULL,
	APP_TTL SMALLINT NOT NULL,
	APP_QOS VARCHAR(50) NOT NULL,
	ENT_CODE CHAR(3) NOT NULL,
	APP_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL
 );

CREATE TABLE SMS_REQUESTS (
	REQ_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REQ_FROM VARCHAR(50) NOT NULL,
	REQ_TO VARCHAR(20) NOT NULL,
	REQ_TTL SMALLINT DEFAULT -1 NOT NULL,
	REQ_DATE_REQUEST TIMESTAMP NOT NULL,
	REQ_DATE_ACKNOWLEDGE TIMESTAMP NULL
);


-- ALTER TABLE BROKERS_CONFIG ADD FOREIGN KEY (BRK_CODE) REFERENCES BROKERS(BRK_CODE);
-- ALTER TABLE BROKERS ADD FOREIGN KEY (CFG_ID) REFERENCES BROKERS_CONFIG(CFG_ID);
ALTER TABLE APPLICATIONS ADD FOREIGN KEY (ENT_CODE) REFERENCES ENTITIES(ENT_CODE);

--INSERT INTO BROKERS_CONFIG (CFG_TOKEN, CFG_REQUEST_ENDPOINT, CFG_NOTIFICATION_ENDPOINT) 
--VALUES('YmFuX3B1c2hfYjczMzE2OkhzYk5YZ0lz', 'https://sms-pp.sapmobileservices.com/cmn/[username]/[username].sms', 'https://c3cam.santanderglobaltech.com/sap/notifications/receive');
INSERT INTO BROKERS (BRK_CODE, BRK_NAME, BRK_ACTIVE, BRK_WEIGHT, BRK_TOKEN, BRK_REQUEST_ENDPOINT, CCC_NOTIFICATION_ENDPOINT) 
VALUES ('SAP', 'SAP Mobile Services', TRUE, 80, 'YmFuX3B1c2hfYjczMzE2OkhzYk5YZ0lz', 'https://sms-pp.sapmobileservices.com/cmn/[username]/[username].sms', 'https://c3cam.santanderglobaltech.com/sap/notifications/receive');
INSERT INTO BROKERS (BRK_CODE, BRK_NAME, BRK_ACTIVE, BRK_WEIGHT, BRK_TOKEN, BRK_REQUEST_ENDPOINT) 
VALUES ('SIN', 'Sinch', TRUE, 20, '4a6892931b1642288dd990850c3fc8b9', 'https://api.mblox.com/xms/v1/produban_ser_eu3/');
--INSERT INTO BROKERS (BRK_CODE, BRK_NAME, BRK_ACTIVE, BRK_WEIGHT) VALUES ('VDF', 'Vodafone España', TRUE, 10);
--INSERT INTO BROKERS (BRK_CODE, BRK_NAME, BRK_ACTIVE, BRK_WEIGHT) VALUES ('MOV', 'Movistar España', TRUE, 50);

INSERT INTO ENTITIES (ENT_CODE, ENT_NAME) VALUES ('CCC', 'Cloud Competence Centre');
INSERT INTO APPLICATIONS (APP_CODE, APP_NAME, APP_TTL, APP_QOS, ENT_CODE) VALUES ('POC', 'Proof of Concept', 3600, 'STANDARD', 'CCC');

