kind: Service
apiVersion: v1
metadata:
  name: c3cam-gateway-svc
  namespace: ccc-cam-poc-dev
spec:
  type: ClusterIP
  selector:
    app: c3cam-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 9000

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3cam-gateway
  namespace: ccc-cam-poc-dev
  labels:
    app: c3cam-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c3cam-gateway
  template:
    metadata:
      labels:
        app: c3cam-gateway
        version: v1
    spec:
      containers:
      - name: c3cam-gateway
        image: registry.global.ccc.srvb.can.paas.cloudcenter.corp/ccc-continuous-delivery/c3cam-poc-gateway:v1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
        ports:
        - containerPort: 9000       

---        

apiVersion: v1
kind: Route
metadata:
  name: c3cam-gateway
  namespace: ccc-cam-poc-dev
spec:
  host: c3cam-gateway-ccc-cam-poc-dev.appls.ocp.ccc.srvb.cn1.paas.cloudcenter.corp
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: c3cam-gateway-svc
    weight: 100
  wildcardPolicy: None
